import { useState, useEffect, useRef } from 'react';
import { Lightbulb, Sparkles, FileText, RotateCcw, ArrowRight } from 'lucide-react';
import { USER_PROFILES, type UserProfileId } from '../../data/userProfiles';
import { EXAMPLE_PROMPTS, type ExamplePrompt } from '../../data/examplePrompts';
import { generateStructuredPrompt } from '../../data/promptStarters';

interface ContentInputProps {
  profileId: UserProfileId | null;
  useCaseId: string | null;
  subject: string;
  structuredPrompt: string;
  additionalDetails: string;
  onSubjectChange: (subject: string) => void;
  onStructuredPromptChange: (structuredPrompt: string) => void;
  onAdditionalDetailsChange: (additionalDetails: string) => void;
}

const MAX_PROMPT_LENGTH = 5000;
const MAX_DETAILS_LENGTH = 2000;

export function ContentInput({
  profileId,
  useCaseId,
  subject,
  structuredPrompt,
  additionalDetails,
  onSubjectChange,
  onStructuredPromptChange,
  onAdditionalDetailsChange,
}: ContentInputProps) {
  const [animationKey, setAnimationKey] = useState(0);
  const [autoGeneratedPrompt, setAutoGeneratedPrompt] = useState('');
  const hasGeneratedRef = useRef(false);

  useEffect(() => {
    setAnimationKey(prev => prev + 1);
  }, [profileId, useCaseId]);

  const profile = profileId ? USER_PROFILES[profileId] : null;
  const useCase = profile?.useCases.find(uc => uc.id === useCaseId);

  // Get example prompts for this profile/useCase combination
  const getExamples = (): ExamplePrompt[] => {
    if (!profileId || !useCaseId) return [];
    const profileExamples = EXAMPLE_PROMPTS[profileId as keyof typeof EXAMPLE_PROMPTS];
    if (!profileExamples) return [];
    const useCaseExamples = profileExamples[useCaseId as keyof typeof profileExamples];
    return (useCaseExamples as ExamplePrompt[] | undefined) || [];
  };
  const examples = getExamples();

  function handleExampleClick(example: { title: string; prompt: string }) {
    onSubjectChange(example.title);
    // Generate structured prompt for this example
    if (profileId && useCaseId) {
      const generated = generateStructuredPrompt(profileId, useCaseId, example.title);
      onStructuredPromptChange(generated);
      setAutoGeneratedPrompt(generated);
    }
    onAdditionalDetailsChange(example.prompt);
  }

  // Generate structured prompt - used by button click and Enter key
  function handleGenerateStructure() {
    if (!subject.trim() || !profileId || !useCaseId) return;

    const generated = generateStructuredPrompt(profileId, useCaseId, subject);
    onStructuredPromptChange(generated);
    setAutoGeneratedPrompt(generated);
    hasGeneratedRef.current = true;
  }

  // Handle Enter key in subject field
  function handleSubjectKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter') {
      e.preventDefault();
      handleGenerateStructure();
    }
  }

  // Generate structured prompt when subject loses focus (only if not already generated)
  function handleSubjectBlur() {
    if (!subject.trim() || !profileId || !useCaseId) return;

    // Only auto-generate if the prompt is empty or matches the previous auto-generated one
    if (!structuredPrompt || structuredPrompt === autoGeneratedPrompt || !hasGeneratedRef.current) {
      handleGenerateStructure();
    }
  }

  // Check if current prompt is the auto-generated version
  const isUsingAutoGenerated = autoGeneratedPrompt && structuredPrompt === autoGeneratedPrompt;
  const hasBeenModified = structuredPrompt && autoGeneratedPrompt && structuredPrompt !== autoGeneratedPrompt;

  function handleRegeneratePrompt() {
    if (profileId && useCaseId && subject.trim()) {
      const generated = generateStructuredPrompt(profileId, useCaseId, subject);
      onStructuredPromptChange(generated);
      setAutoGeneratedPrompt(generated);
    }
  }

  const promptLength = structuredPrompt.length;
  const isNearPromptLimit = promptLength > MAX_PROMPT_LENGTH * 0.8;
  const isOverPromptLimit = promptLength > MAX_PROMPT_LENGTH;

  const detailsLength = additionalDetails.length;
  const isNearDetailsLimit = detailsLength > MAX_DETAILS_LENGTH * 0.8;
  const isOverDetailsLimit = detailsLength > MAX_DETAILS_LENGTH;

  return (
    <div className="animate-fade-in" key={animationKey}>
      {/* Header */}
      <div className="text-center mb-8">
        <h1 className="text-3xl font-semibold text-n46-black tracking-tight mb-3">
          Tell us about your presentation
        </h1>
        <p className="text-n46-gray-500 text-lg">
          {profile && useCase ? (
            <>
              Creating a{' '}
              <span
                className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-sm font-medium"
                style={{
                  backgroundColor: `${profile.color}15`,
                  color: profile.color,
                }}
              >
                {useCase.name}
              </span>
              {' '}presentation
            </>
          ) : (
            'Describe what you want to create'
          )}
        </p>
      </div>

      {/* Form */}
      <div className="max-w-2xl mx-auto space-y-6">
        {/* Subject Input */}
        <div>
          <label
            htmlFor="subject"
            className="block text-sm font-medium text-n46-gray-700 mb-2"
          >
            Subject
          </label>
          <div className="flex gap-2">
            <input
              id="subject"
              type="text"
              value={subject}
              onChange={(e) => onSubjectChange(e.target.value)}
              onBlur={handleSubjectBlur}
              onKeyDown={handleSubjectKeyDown}
              placeholder="Enter the topic of your presentation"
              className="flex-1 px-4 py-3 rounded-xl border border-n46-gray-200 bg-white
                         text-n46-gray-900 placeholder-n46-gray-400
                         focus:outline-none focus:border-n46-blue focus:ring-2 focus:ring-n46-blue/10
                         transition-all duration-150"
            />
            <button
              type="button"
              onClick={handleGenerateStructure}
              disabled={!subject.trim() || !profileId || !useCaseId}
              className={`
                px-4 py-3 rounded-xl font-medium text-sm flex items-center gap-2
                transition-all duration-150
                ${subject.trim() && profileId && useCaseId
                  ? 'bg-n46-blue text-white hover:bg-n46-blue-light'
                  : 'bg-n46-gray-100 text-n46-gray-400 cursor-not-allowed'
                }
              `}
            >
              <span>Enter</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
          <p className="mt-1.5 text-xs text-n46-gray-400">
            Click Enter or press Enter key to generate the presentation structure
          </p>
        </div>

        {/* Structured Prompt Textarea */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label
              htmlFor="structuredPrompt"
              className="block text-sm font-medium text-n46-gray-700"
            >
              Presentation Structure
            </label>
            <div className="flex items-center gap-2">
              {isUsingAutoGenerated && (
                <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-n46-blue/10 text-n46-blue">
                  <Sparkles className="w-3 h-3" />
                  Auto-generated
                </span>
              )}
              {hasBeenModified && (
                <button
                  type="button"
                  onClick={handleRegeneratePrompt}
                  className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium
                             text-n46-gray-500 hover:text-n46-blue hover:bg-n46-blue/10
                             transition-colors"
                >
                  <RotateCcw className="w-3 h-3" />
                  Regenerate
                </button>
              )}
            </div>
          </div>
          <div className="relative">
            <textarea
              id="structuredPrompt"
              value={structuredPrompt}
              onChange={(e) => onStructuredPromptChange(e.target.value)}
              placeholder={subject.trim()
                ? "Your presentation structure will appear here..."
                : "Enter a subject above to generate the structure"
              }
              rows={8}
              className={`
                w-full px-4 py-3 rounded-xl border bg-white
                text-n46-gray-900 placeholder-n46-gray-400 resize-none
                focus:outline-none focus:ring-2 transition-all duration-150
                ${isOverPromptLimit
                  ? 'border-n46-error focus:border-n46-error focus:ring-n46-error/10'
                  : isUsingAutoGenerated
                    ? 'border-n46-blue/30 bg-n46-blue/5 focus:border-n46-blue focus:ring-n46-blue/10'
                    : 'border-n46-gray-200 focus:border-n46-blue focus:ring-n46-blue/10'
                }
              `}
            />
            {/* Character count */}
            <div
              className={`
                absolute bottom-3 right-3 text-xs font-medium
                ${isOverPromptLimit
                  ? 'text-n46-error'
                  : isNearPromptLimit
                    ? 'text-n46-warning'
                    : 'text-n46-gray-400'
                }
              `}
            >
              {promptLength.toLocaleString()} / {MAX_PROMPT_LENGTH.toLocaleString()}
            </div>
          </div>
          <p className="mt-2 text-sm text-n46-gray-500 flex items-start gap-2">
            <FileText className="w-4 h-4 mt-0.5 flex-shrink-0 text-n46-gray-400" />
            <span>
              This structure guides how your presentation is organized. Feel free to edit it.
            </span>
          </p>
        </div>

        {/* Additional Details Textarea */}
        <div>
          <label
            htmlFor="additionalDetails"
            className="block text-sm font-medium text-n46-gray-700 mb-2"
          >
            Your Additional Details <span className="text-n46-gray-400 font-normal">(Optional)</span>
          </label>
          <div className="relative">
            <textarea
              id="additionalDetails"
              value={additionalDetails}
              onChange={(e) => onAdditionalDetailsChange(e.target.value)}
              placeholder="Add specific requirements, focus areas, examples to include, or any other context..."
              rows={4}
              className={`
                w-full px-4 py-3 rounded-xl border bg-white
                text-n46-gray-900 placeholder-n46-gray-400 resize-none
                focus:outline-none focus:ring-2 transition-all duration-150
                ${isOverDetailsLimit
                  ? 'border-n46-error focus:border-n46-error focus:ring-n46-error/10'
                  : 'border-n46-gray-200 focus:border-n46-blue focus:ring-n46-blue/10'
                }
              `}
            />
            {/* Character count */}
            <div
              className={`
                absolute bottom-3 right-3 text-xs font-medium
                ${isOverDetailsLimit
                  ? 'text-n46-error'
                  : isNearDetailsLimit
                    ? 'text-n46-warning'
                    : 'text-n46-gray-400'
                }
              `}
            >
              {detailsLength.toLocaleString()} / {MAX_DETAILS_LENGTH.toLocaleString()}
            </div>
          </div>
          <p className="mt-2 text-sm text-n46-gray-500 flex items-start gap-2">
            <Lightbulb className="w-4 h-4 mt-0.5 flex-shrink-0 text-n46-gray-400" />
            <span>
              The more detail you provide, the better your presentation will be.
              Include specific points, target audience notes, or style preferences.
            </span>
          </p>
        </div>

        {/* Example Prompts */}
        {examples.length > 0 && (
          <div className="pt-4 border-t border-n46-gray-100">
            <div className="flex items-center gap-2 mb-3">
              <Sparkles className="w-4 h-4 text-n46-blue" />
              <span className="text-sm font-medium text-n46-gray-700">
                Try an example
              </span>
            </div>
            <div className="flex flex-wrap gap-2">
              {examples.map((example: ExamplePrompt, index: number) => (
                <button
                  key={index}
                  onClick={() => handleExampleClick(example)}
                  className="px-4 py-2 rounded-lg text-sm font-medium
                             bg-n46-gray-50 text-n46-gray-600
                             hover:bg-n46-blue/10 hover:text-n46-blue
                             border border-n46-gray-200 hover:border-n46-blue/30
                             transition-all duration-150"
                >
                  {example.title}
                </button>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
